### ISSUE TITLE
The single dataset result?

### ISSUE THREAD

**Issue by jainie-max** [mightyzau/LMSeg#1]
Hi , thanks for your great work. I have a question about the result of ADE20k(single dataset training), why the result in table1 40.24 is far lower than the original maskformer paper 46.7 +- 0.6?

**Comment by mightyzau** [comment]
Thank you for your attention. The score of 40.24 is the result of training
the model with 40k steps (160k/4). When the model is trained with 160k
 steps (640k/4), the mIoU on ADE20K is 44.57, as shown in Table 1.

jainie ***@***.***> 于2023年9月26日周二 16:25写道：

**Comment by jainie-max** [comment]
Thank you for your reply! May I ask you another question? During the training process, were the samples for each iteration randomly selected from a dataset?  Or is it training on ADE20k first 0-40k iteration, then training on
 CitySpace 40k-80k iteration such a sequential training

**Comment by mightyzau** [comment]
For each iteration step, we randomly sample data from a dataset.

**Comment by jainie-max** [comment]
Thanks！
